name: PHP Composer
on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        php_version: [ 8.0 ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: phar
          coverage: none
          tools: composer:v2

      - name: Install
        run: composer install --prefer-dist

      - name: Verify
        run: composer verify